---
title: "STA130 Week 3 Class: Data Wrangling"
author: "Samantha-Jo Caetano"
date: "Jan 24, 2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Synchronous class meeting

## Taking up tricky questions from quiz 3


# Loading the coffee ratings data
```{r}
library(tidyverse)
coffee_ratings <- read_csv("coffee_ratings.csv")
```


# Let's look at the distribution of the "color" variable
```{r}
# What type of variable is color? 
# What type of plot do we use to visualize this type of distribution? Barplot
# Let's plot it!

# Lets generate a summary table to look at the exact number of observations for each color of coffee bean

# How many different categories are there really?

# Let's combine similar categories:


# With case_when, any cases we DON'T list automatically lead to values of NA
# This can be a useful feature, but be careful not to forget to list all 
# the cases that you intend to list


# Whenever we use case_when to create/modify a variable, it's a good idea to create a summary table to make sure we did what we wanted to do!


# How can we edit our summary table to look at the mean and median overall coffee ratings (`total_cup_points`), and the standard deviation of the altitude at which the beans were harvested (`altitude_mean_meters`) for each color of coffee bean?


# What are two ways to make the table above more useful?

# What are pros/cons of the two approaches?
```


```{r}
# For the top 5 rated coffees produced in Mexico, produce a tibble containing the overall coffee rating (`total_cup_points`), owner (`owner`), and processing method (`processing_method`)


# What are the 5 countries with the highest average coffee ratings, based on the observations in the coffee ratings dataset?


# Among all countries with at least 10 coffee samples in these data, what are the 5 countries with the highest average coffee ratings?


```








\newpage
# R Code for slides/videos

```{r, include=TRUE, message=FALSE}
library(tidyverse) # Load the tidyverse package to gain access to functions we'll use

# Load data from a csv file using read_csv 
olympics <- read_csv("oly12countries.csv")
glimpse(olympics)
head(olympics)
```




```{r}
olympics %>% 
  filter(athletes_total >= 300)

olympics %>%
  select(Country, athletes_total, gold, silver, bronze)

bigteams <- olympics %>%
  filter(athletes_total >= 300) %>%
  select(Country, athletes_total, gold, silver, bronze)
bigteams ## type the name of the R object to print it

```

```{r, eval=FALSE}
olympics %>%
  filter(athletes_total < 100 & gold > 1) %>%
  select(Country, athletes_total, gold, silver, bronze)
```

```{r}
head(olympics) %>% select(Country, athletes_total, gold, silver, bronze)

olynew <- olympics %>%
  mutate(total_medals = gold + silver + bronze,
         avg_medals = total_medals / athletes_total) %>%
  select(Country, athletes_total, gold, silver, bronze, total_medals, avg_medals)
head(olynew)

olympics %>%
  select(Country, athletes_total, athletes_f, athletes_m) %>%
  head(n=10)

oly_newvar <- olympics %>%
  mutate(majority = case_when(athletes_f > athletes_m ~ "Female",
                              athletes_f == athletes_m ~ "Balanced",
                              athletes_f < athletes_m ~ "Male"),
         total_medals = gold + silver + bronze)

#oly_newvar <- olympics %>%
#  mutate(majority_female = ifelse(athletes_f > athletes_m, yes="Yes", no="No"),
#         total_medals = gold + silver + bronze)

oly_newvar %>% select(Country, athletes_total, 
                      athletes_f, athletes_m, majority, total_medals)
```

```{r}
olynew %>% 
  arrange(desc(total_medals)) %>%
  select(Country, total_medals, avg_medals) %>%
  head()

olynew %>% 
  arrange(desc(avg_medals)) %>%
  select(Country, total_medals, avg_medals) %>%
  head()
```


```{r}
# Summary tables
olympics %>% summarise(n=n(), 
                       mean_gold=mean(gold), 
                       min_gold=min(gold), 
                       max_gold=max(gold))

olympics %>% 
  mutate(teamsize = case_when(athletes_total >= 100 ~ "big",
                              athletes_total < 100 & athletes_total >= 20 ~ "medium",
                              athletes_total < 20 ~ "small")) %>%
  group_by(teamsize) %>%
  summarise(n=n(), 
            mean_gold=mean(gold), 
            min_gold=min(gold), 
            max_gold=max(gold))


oly_newvar %>% 
  group_by(majority) %>%
  summarise(n=n(), 
            mean_gold=mean(gold), 
            min_gold=min(gold), 
            max_gold=max(gold))
```

```{r}
oly_newvar %>%
  group_by(majority) %>%
  summarise(n=n(), 
            mean_medals=mean(gold + silver + bronze), 
            min_medals=min(gold + silver + bronze), 
            max_medals=max(gold + silver + bronze))

oly_newvar %>%
  filter(is.na(majority)) %>%
  select(Country, ISO, athletes_f, athletes_m, gold, silver, bronze, majority)
  
oly_newvar %>%
  filter(!is.na(majority)) %>%
  group_by(majority) %>%
  summarise(n=n(), 
            mean_medals=mean(gold + silver + bronze), 
            min_medals=min(gold + silver + bronze), 
            max_medals=max(gold + silver + bronze))
```



